export const data = [
  {
    page: "TVBrasileira",
    name: "Grandes áudios da TV Brasileira",
    buttons: [
      "Ai",
      "Cavalo",
      "Dança gatinho dança",
      "É brincadeira hein",
      "Ele gosta",
      "IRRAA",
      "Não",
      "RATINHOOOOO",
      "Tome",
      "VIXE",
    ],
  },
  {
    page: "MosquitoGritando",
    name: "Mosquito Gritando",
    buttons: [
      "Alemanha",
      "Atletico",
      "Bahia",
      "Botafogo",
      "Ceará",
      "Corinthians",
      "Cruzeiro",
      "Flamengo",
      "Fluminense",
      "Fortaleza",
      "Palmeiras",
      "Paysandu",
      "Santos",
      "São Paulo",
      "Vasco",
    ],
  },
];
